{!!Html::script('assets/vendors/core/core.js')!!}
{!!Html::script('assets/vendors/chartjs/Chart.min.js')!!}
{!!Html::script('assets/vendors/jquery.flot/jquery.flot.js')!!}
{!!Html::script('assets/vendors/jquery.flot/jquery.flot.resize.js')!!}
{!!Html::script('assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js')!!}
{!!Html::script('assets/vendors/apexcharts/apexcharts.min.js')!!}
{!!Html::script('assets/vendors/progressbar.js/progressbar.min.js')!!}
{!!Html::script('assets/vendors/feather-icons/feather.min.js')!!}
{!!Html::script('assets/js/template.js')!!}
{!!Html::script('assets/js/dashboard.js')!!}
{!!Html::script('assets/js/datepicker.js')!!}
{!!Html::script('assets/vendors/dropify/dist/dropify.min.js')!!}
{!!Html::script('assets/js/dropify.js')!!}
{!!Html::script('assets/vendors/jquery-validation/jquery.validate.min.js')!!}
{!!Html::script('assets/js/form-validation.js')!!}
{!!Html::script('assets/vendors/sweetalert2/sweetalert2.min.js')!!}
{!!Html::script('assets/js/sweet-alert.js')!!}
{!!Html::script('assets/vendors/owl.carousel/owl.carousel.min.js')!!}
{!!Html::script('assets/js/carousel.js')!!}
{!!Html::script('assets/vendors/datatables.net/jquery.dataTables.js')!!}
{!!Html::script('assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js')!!}
{!!Html::script('assets/js/data-table.js')!!}
{!!Html::script('assets/js/client.js')!!}
